#pragma once

#include <functional>
#include "string_converter.hpp"

namespace calyx
{

    /**
     * @brief Stores commonly used error message factories. Note that these are not proper error objects!
     *
     */
    class Errors
    {
        static const std::function<String_t(const String_t &, const StringConverter<String_t> &)> undefinedRule;

        static const std::function<String_t(const String_t &, const StringConverter<String_t> &)> undefinedFilter;

        static const std::function<String_t(const String_t &, const StringConverter<String_t> &)> incorrectFilterSignature;
    };

    /**
     * @brief Stores error codes/messages in a C-like way to keep interoperability with UE and its lack of exceptions.
     *
     * Errors are generated by setting an error message with setError(), and then early returning with an arbitrary default
     * value.
     *
     * Should always be passed by reference.
     */
    class Error
    {
    public:
        /**
         * @brief Construct a new Error object with no errors
         *
         */
        Error();

        ~Error();

        /**
         * @brief Errors should be passed by reference. The copy constructor is deleted to enforce this.
         *
         * @param old
         */
        Error(const Error &old) = delete;

        /**
         * @brief Errors should be passed by reference. The assignment operator is deleted to enforce this.
         *
         * @param other
         * @return Error&
         */
        Error &operator=(const Error &other) = delete;

        /**
         * @brief Determine if errors are present. Errors are present if and only if setError() has been called on this instance.
         *
         * @return true Returns true if an error is present
         * @return false Returns false if an error is not present
         */
        bool hasError() const;

        /**
         * @brief Get the error message.
         *
         * @return const String_t& Returns the message if an error is present, otherwise returns an empty string.
         */
        const String_t &getMessage() const;

        /**
         * @brief Sets an error message to the given message, and also sets hasError to true.
         *
         * @param message The error message
         */
        void setError(String_t message);

    private:
        String_t _message;
        bool _hasError;
    };
}
