# Automatically build the project and run its tests on every push and pull request.

name: build
on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
            
            -   name: Install xmake
                run: curl -fsSL https://xmake.io/shget.text | bash

            -   name: Build
                run: xmake -y

            -   name: Run tests
                run: xmake run test