# Automatically build the project and run its tests on every push and pull request.

name: build
on: [pull_request, push]

jobs:
    build:
        runs-on: ubtuntu-latest
        steps:
            -   name: checkout repo
                uses: actions/checkout@v2

            -   name: build and run
                run: xmake
                
            -   name: Run tests
                run: xmake run test